[IBS-69] Test & migrate groups (student)
Kianoosh76/IBS pull request #69
Opened 2024-04-05 11:35 UTC by hezhongq

## Description
- Refactored Group endpoints for Students.

## Changes Made
- Refactored following endpoints`
  - `module/group/student/accept.js`
  - `module/group/student/check.js`
  - `module/group/student/create.js`
  - `module/group/student/disinvite.js`
  - `module/group/student/invite.js`
  - `module/group/student/leave.js`
  - `module/group/student/reject.js`
- Enabled the disinvite endpoint for a student in `backend/route/student.js`for refactoring purposes

## Test Guidelines
- In `/backend/` run the following and ensure that they all passes:
 - `npm test group_student_accept`
 - `npm test group_student_check`
 - `npm test group_student_create`
 - `npm test group_student_disinvite`
 - `npm test group_student_invite`
 - `npm test group_student_leave`
 - `npm test group_student_reject`

## Checklist

### For PR author:
- [ ] Reviewed code changes.
- [ ] Tested changes locally.
- [ ] Added appropriate comments.
- [ ] Ensured consistent code style and formatting.
- [ ] Included unit/integration tests.
- [ ] Handled edge cases appropriately.
- [ ] Celebrated accomplishments 🎉

### For PR reviewer:
- [ ] Reviewed code changes.
- [ ] Tested changes locally.
- [ ] Verified clear and helpful comments.
- [ ] Ensured code style aligns with standards.
- [ ] Examined test coverage.
- [ ] Provided feedback on potential edge cases.

2024-04-10 17:59 UTC, DomiVesalius requested changes
## Issues
There are a few issues in the way previous SQL queries have been translated to ORM calls that need to be fixed.

Also noticed that this should include refactor for `module/group/student/leave.js` however it remains unchanged. I see that you have pushed a test and seeder file for that endpoint so I am assuming you simply forgot to push those changes.

## Tests
- Tests for accept, check, create, disinvite, invite, and reject pass
- Test for leave fails due to missing refactored version

2024-04-10 17:59 UTC, DomiVesalius commented on backend/lib/version_control/MockVCS.js
> +        return { success: true, url: vcs_url };
I remember helping you debug an issue where the url was not showing up in the response body.

This return value needs to be exactly the same as the one in `GitlabVCS` so you cannot change it from `gitlab_url` to `url`.  Change this back to `gitlab_url` and modify any places that make use of this return value accordingly.

2024-04-10 17:59 UTC, DomiVesalius commented on backend/migrations/20231008081024-create-course.js
> +    // await queryInterface.removeConstraint('courses', 'custom_fkey_course_id');
Remove commented code

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/accept.js
> +const { QueryTypes } = require('sequelize');
Remove unused import

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/check.js
> +		console.log({ username });
Remove log

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/check.js
> -	}
I think you still need to check for this case.

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/check.js
> +		const status = groupUser.dataValues.status;
remove unused variable

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/check.js
> +		});
I don't think this block of code is the correct translation of the SQL statement it is trying to mimic:
```sql
SELECT * FROM course_" + res.locals["course_id"] + ".group_user WHERE username = ($1) AND task = ($2)
```

You forgot to specify the task in the `where` clause. Currently, if the user was in multiple groups across several courses with several tasks, then this might end up choosing the incorrect group that you are checking for.

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/create.js
> -						res.status(409).json({ message: "You can join at most one group for each task." });
The refactored version should include this logic as well

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/create.js
> +		const newGroup = await Group.create({ task_id: taskInstance.id });
Refer to previous comment. You must check if the user is already in a group before creating a new one.

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/disinvite.js
> +const { GroupUser, Group } = require('../../../models');
Remove unused `Group` model from import

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/disinvite.js
> +		const { task } = res.locals.task;
Unused variable

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/disinvite.js
> +		});
Same issue pointed out by previous comment. I don't think this is a direct translation of
```sql
SELECT * FROM course_" + res.locals["course_id"] + ".group_user WHERE task = ($1) AND username = ($2) AND status = 'confirmed'
```

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/invite.js
> +		});
This isn't a direct translation of
```sql
SELECT * FROM course_" + res.locals["course_id"] + ".group_user WHERE task = ($1) AND username = ($2)
```

You need to include username in your where clause otherwise all this statement does is get every confirmed group_user row for a specific task.

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/invite.js
>  		}
Should also check if a user with the given username exists in the database to cover this case from the original version: https://github.com/Kianoosh76/IBS/blob/d3317ecf1d68513b00df81e966ee0c42b356d373/backend/module/group/student/invite.js#L58

2024-04-10 17:59 UTC, DomiVesalius commented on backend/module/group/student/reject.js
> +			return res.status(400).json({ message: "Task not found." });
Original message should be preserved:

https://github.com/Kianoosh76/IBS/blob/d3317ecf1d68513b00df81e966ee0c42b356d373/backend/module/group/student/reject.js#L12

2024-04-15 13:55 UTC, hezhongq commented on backend/module/group/student/invite.js
> +		});
I have taken a different approach of first finding all users in the group, then create invitation if the following check passes:
1. current user has access to invite other user(user who initiates the invitation is already in the group)
2. if usersInGroup.length has not yet reach max number of available user per group
This approach helps with getting the headcount of students per group

2024-04-15 13:59 UTC, hezhongq commented on backend/module/group/student/invite.js
>  		}
When we reach this line it would have already passed the username check, where if the task with given username does not exist then it could just return with the "You don't have access to invite." message instead. We may not necessarily need to reveal much info regarding our data in the database

2025-01-05 09:45 UTC, mohtashim-ali commented
I have reviewed the PR and it seems to be completed, just needs to be merged. All tests pass with latest changes from previous PRs merged.

2025-01-07 17:40 UTC, Kianoosh76 approved these changes

2025-01-07 17:40 UTC, merged